domotz/custom-driver

- examples/http/iq4e_sensors.js
The new example driver (http based) collects Sensor items data and stores them in custom driver variables
> SSB-1272: Added a custom driver example for trend IQ4E controller

- examples/spec/mysql_spec.js
- examples/ssh/mysql.js
@GeorgiTsatsev I improved and commented the MySQL driver, plus I added some Jasmine tests for  the quite complex parsing of the command outputs. Still, more tests could be added, but I want to iron out some details with you first.
> Improved MySQLdriver and added tests

- sandbox_emulator/lib/constants.js
- sandbox_emulator/lib/crypto.js
- sandbox_emulator/lib/d.js
- sandbox_emulator/lib/variable.js
crypto integration
createVariable in D namespace
> crypto integration

- examples/ssh/control4_zigbee_devices.js
- examples/winrm/windows_services.js
- sandbox_emulator/.eslintrc.js
- sandbox_emulator/lib/d.js
- sandbox_emulator/lib/platform.js
- sandbox_emulator/package.json
fix drivers compatibilty with es5 syntax
fix D namespace
> Fix emulator bugs

- examples/http/aws_cloudWatch_metric.js
- examples/http/aws_cloudwatch_metric.js
The driver designed to retrieve CloudWatch metrics for various AWS services
> CD-51: AWS CloudWatch metric

- examples/snmp/apc_ups_temperature_humidity.js
- examples/snmp/apc_ups_temperature_humidity.json
This Driver monitor the UPS Temperatury and Humidity
> CD-121: APC-UPS- Temperature and Humidity - custom driver

- examples/ssh/xclarity_processors_health.js
- examples/ssh/xclarity_processors_health.json
> CD-174: XClarity (Lenovo) Processors Health

- examples/http/bulk_ssl_certificate.js
- examples/http/bulk_ssl_certificate.json
- examples/http/ssl_certificate.js
- examples/http/ssl_certificate.json
- sandbox_emulator/lib/device.js
This PR depends on version 1.14 of the sandbox library so we will have to wait that release before merging this one
> BT-4090: added getTLSCertificate function - On hold, waiting for agent 5.4.1-b001

- examples/http/hpe_msa_san_hardware_sensors_charge.js
- examples/http/hpe_msa_san_hardware_sensors_charge.json
Reverts domotz/custom-driver#245
> Revert "Revert "CD-326: HPE MSA SAN - HW Sensors - Charge - REST API""

- examples/winrm/windows_services.js
- examples/winrm/windows_services.json
- Bump script version in JSON file
- Remove the SQL Server Express service from the list of default services
> CD-359 - Make Windows services script work with services containing $  in the name

- examples/http/bluos.js
- examples/http/clearone_convergence.js
- examples/http/clearone_convergence.json
- examples/winrm/sql_server.js
- examples/winrm/sql_server.json
- examples/winrm/windows_logical_disks.js
- CD-342 - SQLServer Status Monitoring
- CD-374 - Ubiquiti EdgeRouter - Configuration Management Script
- CD-378 - Make protocol and port configurable on Clearone Convergence script
> Release 21-05-2024

- examples/winrm/windows_firewall_rules.js
CD-122-fix
- Replace None values with N/A
> CD-122-fix

- examples/http/esxi_cpu_and_memory_information.json
- examples/http/esxi_cpu_details.json
- examples/http/esxi_datastores.json
- examples/http/esxi_file_system_volume.json
- examples/http/esxi_general_information.json
- examples/http/esxi_network_details.json
- examples/http/esxi_network_dns_configuration.json
- examples/http/esxi_network_physical_nics_configuration.json
- examples/http/esxi_network_port_group_configuration.json
- examples/http/esxi_network_virtual_nics_configuration.json
- examples/http/esxi_network_virtual_switch_configuration.json
- examples/http/esxi_services.json
- examples/http/esxi_virtual_machines.json
> Change ESXi scripts category

- examples/http/zoom_devices_list.js
- examples/http/zoom_devices_list.json
- examples/http/zoom_workspace_usage.json
> Release 30-01-2025 bump scripts version

- examples/http/palo_alto_firewall_backup_configuration.json
- examples/http/pfSense_configuration_backup.json
- examples/ssh/edge_os_configuration_backup.json
- examples/ssh/fs_switch_configuration_backup.json
- examples/ssh/huawei_switch_configuration_backup.json
> CD-636 - Bump versions

- examples/http/sony_tv.json
- examples/http/zoom_devices_list.json
Bump script versions for Sony TV and Zoom devices list
> CD-CD-bump-script-v

- examples/http/sonicwall_firewall_backups_configuration.js
- examples/http/sonicwall_firewall_backups_configuration.json
Fixed ignored lines regular expression
> CD 690 sonic wall configuration backup   fix ignored lines regular expressions

- examples/ssh/cisco_ios_configuration_backup_tftp.js
- examples/ssh/cisco_ios_configuration_backup_tftp.json
CD-697 - Cisco IOS TFTP Configuration Backup
> CD-697 - Cisco IOS TFTP Configuration Backup

- examples/ssh/vyatta_vyos_configuration_backup.js
- examples/ssh/vyatta_vyos_configuration_backup.json
- logos/vyos.svg
CD-703 - Vyatta VyOS - Configuration Backup
> CD-703 - Vyatta VyOS - Configuration Backup

- examples/http/teams_rooms_device_status.js
- examples/http/teams_rooms_ongoing_meetings_participants.js
CD-691 - Fixed column headers creation
CD-681 - Fixed column headers creation
> Fixed column headers creation

- examples/ssh/edge_os_configuration_backup.js
- examples/ssh/edge_os_configuration_backup.json
- examples/ssh/edge_switch_configuration_backup.js
- examples/ssh/edge_switch_configuration_backup.json
CD-704 - EdgeSwitch - Configuration Backup
> CD-704 - EdgeSwitch - Configuration Backup

- examples/http/teams_rooms_status.json
> CD-687 - Fix script title

- examples/http/teams_rooms_ongoing_meetings_participants.js
- examples/http/teams_rooms_ongoing_meetings_participants.json
- examples/http/teams_rooms_status.json
CD-681 - Fix table headers and parameter name
> CD-681 - Fix table headers and parameter name
